# Generated by Django 4.2.7 on 2023-11-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_servicoadicional_remove_servico_protocolo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='protocole',
            new_name='protocolo',
        ),
    ]
